# ansible-playbook -v -i ~/ansible/hosts /playbooks/setup-camera-pix-e-gif.yml
---
- hosts: pix-e-gif-cam
  gather_facts: yes
  vars:

    boot_config_options:

      # Disable Camera LED 1 is disabled, 0 is enabled
      - regexp: "^#?disable_camera_led"
        line: "disable_camera_led=0"

  tasks:

    - name: Set the GPU memory split value via raspi-config - 128 iS the minimum for the camera
      become: yes
      command: raspi-config nonint do_memory_split gpu_mem_1024=128

    - name: Enable the camera via raspi-config
      become: yes
      command: raspi-config nonint do_camera 0
      
    # Run apt-get update and apt-get upgrade 
    - include_tasks: ../tasks/update.yml
      tags: update

    # Install dependancies from apt
    - name: Install dependancies from apt
      become: yes
      apt: name={{item}} state=installed
      with_items:
        - git-core
        - python-picamera
        - graphicsmagick

    # Get GifCam library from github
    - name: Get GifCam library from github
      git:
        repo: https://github.com/nickbrewer/gifcam.git
        dest: /home/pi/gifcam